### PR TITLE
NPE in logs for incorrect login requests

### PR DESCRIPTION
**Pull request by vidulkeyt**

### CODE REVIEW

**Comment by JKAUSHALYA** [comment]
NPE is fixed. But I think it is better to come with a different approach other than appending a empty string to null.

**Comment by cdwijayarathna** [comment]
@vidulkeyt Is there any jira associated with this issue, with steps to reproduce it? If not can you please create a jira at https://wso2.org/jira/browse/IDENTITY with steps to reproduce this in a latest pack?

**Comment by vidulkeyt** [comment]
I can't provide steps, this issue is reproduced from time to time without any specific scenario just usual login steps results in NPE. I will look into it

**Comment by vidulkeyt** [comment]
It looks like when user opens /oauth2/authorize first time IS sometimes decides that the user is looked (but the user hasn't entered login/password yet). I think it can be caused by some flags which are stored in thread local variables, but I'm not sure.
I've revised my previous fix to decrease failures count while opening login page.

**Pull request closed without merging**
